In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("darkgrid")

In [2]:
data = pd.read_csv('../../data/processed/trial4.csv')

In [3]:
data

,logkpl,Compound,SMILES,Texpi,ALogP,ALogp2,AMR,apol,nAcid,naAromAtom,...,MW,WTPT-1,WTPT-2,WTPT-3,WTPT-4,WTPT-5,WPATH,WPOL,XLogP,Zagreb
0,-3.55,Urea,C(=O)(N)N,312,-1.0421,1.085972,13.1426,7.429172,0,0,...,60.055310,6.732051,1.683013,6.732051,2.244017,4.488034,9.0,0.0,-1.686,12.0
1,-3.69,Urea,C(=O)(N)N,312,-1.0421,1.085972,13.1426,7.429172,0,0,...,60.055310,6.732051,1.683013,6.732051,2.244017,4.488034,9.0,0.0,-1.686,12.0
2,-3.83,Urea,C(=O)(N)N,312,-1.0421,1.085972,13.1426,7.429172,0,0,...,60.055310,6.732051,1.683013,6.732051,2.244017,4.488034,9.0,0.0,-1.686,12.0
3,-3.95,Urea,C(=O)(N)N,312,-1.0421,1.085972,13.1426,7.429172,0,0,...,60.055310,6.732051,1.683013,6.732051,2.244017,4.488034,9.0,0.0,-1.686,12.0
4,-3.93,Urea,C(=O)(N)N,312,-1.0421,1.085972,13.1426,7.429172,0,0,...,60.055310,6.732051,1.683013,6.732051,2.244017,4.488034,9.0,0.0,-1.686,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,-3.68,Methylglucose,COC(C(C=O)O)C(C(CO)O)O,310,-2.2754,5.177445,42.1719,26.467102,0,0,...,194.182751,24.142258,1.857097,14.920659,14.920659,0.000000,252.0,18.0,-2.806,54.0
441,-1.56,Eugenol,COC1=C(C=CC(=C1)CC=C)O,305,2.5541,6.523427,48.5026,27.205516,0,6,...,164.201458,23.427332,1.952278,5.304497,5.304497,0.000000,204.0,15.0,2.556,54.0
442,-1.59,Eugenol,COC1=C(C=CC(=C1)CC=C)O,305,2.5541,6.523427,48.5026,27.205516,0,6,...,164.201458,23.427332,1.952278,5.304497,5.304497,0.000000,204.0,15.0,2.556,54.0
443,-2.07,Methyl methanesulfonate,COS(=O)(=O)C,305,-0.3747,0.140400,21.6541,12.826758,0,0,...,110.133416,10.465990,1.744332,10.298097,7.194544,0.000000,28.0,3.0,-0.869,24.0
444,-1.91,Methyl methanesulfonate,COS(=O)(=O)C,305,-0.3747,0.140400,21.6541,12.826758,0,0,...,110.133416,10.465990,1.744332,10.298097,7.194544,0.000000,28.0,3.0,-0.869,24.0

In [4]:
# we have 45 duplicated values
data.duplicated().sum()

28

In [5]:
# dropping duplicated values
data_clean = data.drop_duplicates().reset_index(drop=True)

In [6]:
data_clean.duplicated().sum()

0

In [7]:
data_clean.shape

(417, 226)

In [14]:
df = data_clean#.drop("SMILES", axis=1)
df

,logkpl,Compound,SMILES,Texpi,ALogP,ALogp2,AMR,apol,nAcid,naAromAtom,...,MW,WTPT-1,WTPT-2,WTPT-3,WTPT-4,WTPT-5,WPATH,WPOL,XLogP,Zagreb
0,-3.55,Urea,C(=O)(N)N,312,-1.0421,1.085972,13.1426,7.429172,0,0,...,60.055310,6.732051,1.683013,6.732051,2.244017,4.488034,9.0,0.0,-1.686,12.0
1,-3.69,Urea,C(=O)(N)N,312,-1.0421,1.085972,13.1426,7.429172,0,0,...,60.055310,6.732051,1.683013,6.732051,2.244017,4.488034,9.0,0.0,-1.686,12.0
2,-3.83,Urea,C(=O)(N)N,312,-1.0421,1.085972,13.1426,7.429172,0,0,...,60.055310,6.732051,1.683013,6.732051,2.244017,4.488034,9.0,0.0,-1.686,12.0
3,-3.95,Urea,C(=O)(N)N,312,-1.0421,1.085972,13.1426,7.429172,0,0,...,60.055310,6.732051,1.683013,6.732051,2.244017,4.488034,9.0,0.0,-1.686,12.0
4,-3.93,Urea,C(=O)(N)N,312,-1.0421,1.085972,13.1426,7.429172,0,0,...,60.055310,6.732051,1.683013,6.732051,2.244017,4.488034,9.0,0.0,-1.686,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,-3.68,Methylglucose,COC(C(C=O)O)C(C(CO)O)O,310,-2.2754,5.177445,42.1719,26.467102,0,0,...,194.182751,24.142258,1.857097,14.920659,14.920659,0.000000,252.0,18.0,-2.806,54.0
413,-1.56,Eugenol,COC1=C(C=CC(=C1)CC=C)O,305,2.5541,6.523427,48.5026,27.205516,0,6,...,164.201458,23.427332,1.952278,5.304497,5.304497,0.000000,204.0,15.0,2.556,54.0
414,-1.59,Eugenol,COC1=C(C=CC(=C1)CC=C)O,305,2.5541,6.523427,48.5026,27.205516,0,6,...,164.201458,23.427332,1.952278,5.304497,5.304497,0.000000,204.0,15.0,2.556,54.0
415,-2.07,Methyl methanesulfonate,COS(=O)(=O)C,305,-0.3747,0.140400,21.6541,12.826758,0,0,...,110.133416,10.465990,1.744332,10.298097,7.194544,0.000000,28.0,3.0,-0.869,24.0
416,-1.91,Methyl methanesulfonate,COS(=O)(=O)C,305,-0.3747,0.140400,21.6541,12.826758,0,0,...,110.133416,10.465990,1.744332,10.298097,7.194544,0.000000,28.0,3.0,-0.869,24.0

In [17]:
def return_correlated_features(df, lower_threshold, upper_threshold):
    corr_matrix = df.corr()

    #the matrix is symmetric so we need to extract upper triangle matrix without diagonal (k = 1)

    sol = (corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
                    .stack()
                    .sort_values(ascending=False))

    filtered_sol = sol[(sol >= lower_threshold) & (sol <= upper_threshold)]

    filtered_sol_df = pd.DataFrame(filtered_sol)
    filtered_sol_df.rename({0: "Correlation"}, inplace=True)

    return filtered_sol_df

In [18]:
temp = return_correlated_features(df.drop(['khs.ssssB', 'khs.ssssBe', 'SCH-4', 'C1SP1', 'khs.tsC', 'khs.sssNH', 'khs.sI', 'SCH-3'],axis=1), lower_threshold=0.95, upper_threshold=1)
temp

C:\Users\user\AppData\Local\Temp\ipykernel_7440\2600226952.py:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  corr_matrix = df.corr()

                       0
VCH-4 nRings3   1.000000
VCH-3 VCH-4     1.000000
      nRings3   1.000000
Fsp3  HybRatio  0.999995
VP-6  VP-7      0.999117
...                  ...
nAtom ECCEN     0.950224
SP-5  VP-1      0.950217
VABC  WPOL      0.950200
SPC-6 VP-4      0.950014
SCH-6 SP-6      0.950001

[635 rows x 1 columns]

In [19]:
one = []
second = []
for t in temp.index:
    one.append(t[0])
    second.append(t[0])

In [20]:
reduced_df = df.drop(['khs.ssssB', 'khs.ssssBe', 'SCH-4', 'C1SP1', 'khs.tsC', 'khs.sssNH', 'khs.sI', 'SCH-3'] + one, axis=1)
reduced_df

,logkpl,Compound,SMILES,Texpi,ALogp2,nAcid,nAromBond,ATSc2,ATSc3,ATSc4,...,nRings9,TopoPSA,VAdjMat,WTPT-2,WTPT-3,WTPT-4,WTPT-5,WPATH,XLogP,Zagreb
0,-3.55,Urea,C(=O)(N)N,312,1.085972,0,0,-0.116019,0.023614,0.000000,...,0,69.11,2.584963,1.683013,6.732051,2.244017,4.488034,9.0,-1.686,12.0
1,-3.69,Urea,C(=O)(N)N,312,1.085972,0,0,-0.116019,0.023614,0.000000,...,0,69.11,2.584963,1.683013,6.732051,2.244017,4.488034,9.0,-1.686,12.0
2,-3.83,Urea,C(=O)(N)N,312,1.085972,0,0,-0.116019,0.023614,0.000000,...,0,69.11,2.584963,1.683013,6.732051,2.244017,4.488034,9.0,-1.686,12.0
3,-3.95,Urea,C(=O)(N)N,312,1.085972,0,0,-0.116019,0.023614,0.000000,...,0,69.11,2.584963,1.683013,6.732051,2.244017,4.488034,9.0,-1.686,12.0
4,-3.93,Urea,C(=O)(N)N,312,1.085972,0,0,-0.116019,0.023614,0.000000,...,0,69.11,2.584963,1.683013,6.732051,2.244017,4.488034,9.0,-1.686,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,-3.68,Methylglucose,COC(C(C=O)O)C(C(CO)O)O,310,5.177445,0,0,-0.149202,-0.333960,0.084389,...,0,107.22,4.584963,1.857097,14.920659,14.920659,0.000000,252.0,-2.806,54.0
413,-1.56,Eugenol,COC1=C(C=CC(=C1)CC=C)O,305,6.523427,0,6,-0.103526,-0.058044,0.090303,...,0,29.46,4.584963,1.952278,5.304497,5.304497,0.000000,204.0,2.556,54.0
414,-1.59,Eugenol,COC1=C(C=CC(=C1)CC=C)O,305,6.523427,0,6,-0.103526,-0.058044,0.090303,...,0,29.46,4.584963,1.952278,5.304497,5.304497,0.000000,204.0,2.556,54.0
415,-2.07,Methyl methanesulfonate,COS(=O)(=O)C,305,0.140400,0,0,-0.182756,0.082199,-0.044057,...,0,51.75,3.321928,1.744332,10.298097,7.194544,0.000000,28.0,-0.869,24.0
416,-1.91,Methyl methanesulfonate,COS(=O)(=O)C,305,0.140400,0,0,-0.182756,0.082199,-0.044057,...,0,51.75,3.321928,1.744332,10.298097,7.194544,0.000000,28.0,-0.869,24.0

In [21]:
data_clean = data_clean.drop(['khs.ssssB', 'khs.ssssBe', 'SCH-4', 'C1SP1', 'khs.tsC', 'khs.sssNH', 'khs.sI', 'SCH-3'] + one, axis=1)

In [22]:
data_clean

,logkpl,Compound,SMILES,Texpi,ALogp2,nAcid,nAromBond,ATSc2,ATSc3,ATSc4,...,nRings9,TopoPSA,VAdjMat,WTPT-2,WTPT-3,WTPT-4,WTPT-5,WPATH,XLogP,Zagreb
0,-3.55,Urea,C(=O)(N)N,312,1.085972,0,0,-0.116019,0.023614,0.000000,...,0,69.11,2.584963,1.683013,6.732051,2.244017,4.488034,9.0,-1.686,12.0
1,-3.69,Urea,C(=O)(N)N,312,1.085972,0,0,-0.116019,0.023614,0.000000,...,0,69.11,2.584963,1.683013,6.732051,2.244017,4.488034,9.0,-1.686,12.0
2,-3.83,Urea,C(=O)(N)N,312,1.085972,0,0,-0.116019,0.023614,0.000000,...,0,69.11,2.584963,1.683013,6.732051,2.244017,4.488034,9.0,-1.686,12.0
3,-3.95,Urea,C(=O)(N)N,312,1.085972,0,0,-0.116019,0.023614,0.000000,...,0,69.11,2.584963,1.683013,6.732051,2.244017,4.488034,9.0,-1.686,12.0
4,-3.93,Urea,C(=O)(N)N,312,1.085972,0,0,-0.116019,0.023614,0.000000,...,0,69.11,2.584963,1.683013,6.732051,2.244017,4.488034,9.0,-1.686,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,-3.68,Methylglucose,COC(C(C=O)O)C(C(CO)O)O,310,5.177445,0,0,-0.149202,-0.333960,0.084389,...,0,107.22,4.584963,1.857097,14.920659,14.920659,0.000000,252.0,-2.806,54.0
413,-1.56,Eugenol,COC1=C(C=CC(=C1)CC=C)O,305,6.523427,0,6,-0.103526,-0.058044,0.090303,...,0,29.46,4.584963,1.952278,5.304497,5.304497,0.000000,204.0,2.556,54.0
414,-1.59,Eugenol,COC1=C(C=CC(=C1)CC=C)O,305,6.523427,0,6,-0.103526,-0.058044,0.090303,...,0,29.46,4.584963,1.952278,5.304497,5.304497,0.000000,204.0,2.556,54.0
415,-2.07,Methyl methanesulfonate,COS(=O)(=O)C,305,0.140400,0,0,-0.182756,0.082199,-0.044057,...,0,51.75,3.321928,1.744332,10.298097,7.194544,0.000000,28.0,-0.869,24.0
416,-1.91,Methyl methanesulfonate,COS(=O)(=O)C,305,0.140400,0,0,-0.182756,0.082199,-0.044057,...,0,51.75,3.321928,1.744332,10.298097,7.194544,0.000000,28.0,-0.869,24.0

In [23]:
data_clean.to_csv("../../data/final/clean_trial4.csv", index=False)